const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Behaviors.Flash,
		C3.Plugins.AJAX,
		C3.Plugins.Mouse,
		C3.Plugins.Internationalization,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Internationalization.Exps.Lookup,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetPersisted,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Acts.MoveLayer,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Internationalization.Acts.LoadFromJSON,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade
	];
};
self.C3_JsPropNameTable = [
	{tx_generico: 0},
	{tx_Sim: 0},
	{tx_Nao: 0},
	{tx_ReniciarGSP: 0},
	{tx_ranges_iguais: 0},
	{secao_piscando: 0},
	{Senóide: 0},
	{bt_home: 0},
	{bt_reiniciar: 0},
	{bg_texto: 0},
	{erro_codigo_1: 0},
	{Esmaecer: 0},
	{treino_como_atualizar_SKU: 0},
	{Piscar: 0},
	{bg_pisca_vermelho: 0},
	{AJAX: 0},
	{Mouse: 0},
	{tradutor: 0},
	{Navegador: 0},
	{ranges_iguais: 0},
	{seção_piscando: 0},
	{bg_texto2: 0},
	{camadaAtiva: 0},
	{idiomaAtivo: 0}
];

self.InstanceType = {
	tx_generico: class extends self.ITextInstance {},
	tx_Sim: class extends self.ITextInstance {},
	tx_Nao: class extends self.ITextInstance {},
	tx_ReniciarGSP: class extends self.ITextInstance {},
	tx_ranges_iguais: class extends self.ITextInstance {},
	secao_piscando: class extends self.ITextInstance {},
	bt_home: class extends self.ISpriteInstance {},
	bt_reiniciar: class extends self.ISpriteInstance {},
	bg_texto: class extends self.ISpriteInstance {},
	erro_codigo_1: class extends self.ISpriteInstance {},
	treino_como_atualizar_SKU: class extends self.ISpriteInstance {},
	bg_pisca_vermelho: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	tradutor: class extends self.IInstance {},
	Navegador: class extends self.IInstance {},
	ranges_iguais: class extends self.ISpriteInstance {},
	seção_piscando: class extends self.ISpriteInstance {},
	bg_texto2: class extends self.ISpriteInstance {}
}