const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Internationalization,
		C3.Plugins.AJAX,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.MoveLayer,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Internationalization.Exps.Lookup,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Internationalization.Acts.LoadFromJSON,
		C3.Plugins.AJAX.Exps.LastData
	];
};
self.C3_JsPropNameTable = [
	{tx1: 0},
	{txSimples: 0},
	{tx_PG: 0},
	{tx2: 0},
	{txSim: 0},
	{txNao: 0},
	{bloqueio_por_check_in_: 0},
	{Codigo1_cadastrar_receita: 0},
	{conformidade_zerada_pt_created: 0},
	{Erro_codigo_2: 0},
	{Maquina_rodando_conformidade_com_erro: 0},
	{maquina_rodando_no_result: 0},
	{No_Result_Rosa_No_Result_Vermelho: 0},
	{ordem_setada_errada: 0},
	{bloqueio_por_check_in: 0},
	{parametro_no_piVision_fora_plano: 0},
	{ranges_iguais: 0},
	{seção_piscando: 0},
	{erro_criar_receita_erro_memoria: 0},
	{erro_criar_receita_variavel_nao_encontrada: 0},
	{ErroAoCriarReceita_falha_data_base: 0},
	{pi_point_nao_atualiza: 0},
	{receita_codigo_cadastrado_pt_created: 0},
	{receita_codigo_cadastrado_pt_created_: 0},
	{tudo_configurado_mas_falta_subir_valores: 0},
	{valor_pi_vision_diferente_valor_maquina: 0},
	{variavel_desativada_afetando_conformidade: 0},
	{variavel_desativada_afetando_conformidade2: 0},
	{bg: 0},
	{bg2: 0},
	{Senóide: 0},
	{bt_reiniciar: 0},
	{seta: 0},
	{bg3: 0},
	{tradutor: 0},
	{AJAX: 0},
	{Mouse: 0},
	{bt_home: 0},
	{Navegador: 0},
	{paginaAtiva: 0}
];

self.InstanceType = {
	tx1: class extends self.ITextInstance {},
	txSimples: class extends self.ITextInstance {},
	tx_PG: class extends self.ITextInstance {},
	tx2: class extends self.ITextInstance {},
	txSim: class extends self.ITextInstance {},
	txNao: class extends self.ITextInstance {},
	bloqueio_por_check_in_: class extends self.ISpriteInstance {},
	Codigo1_cadastrar_receita: class extends self.ISpriteInstance {},
	conformidade_zerada_pt_created: class extends self.ISpriteInstance {},
	Erro_codigo_2: class extends self.ISpriteInstance {},
	Maquina_rodando_conformidade_com_erro: class extends self.ISpriteInstance {},
	maquina_rodando_no_result: class extends self.ISpriteInstance {},
	No_Result_Rosa_No_Result_Vermelho: class extends self.ISpriteInstance {},
	ordem_setada_errada: class extends self.ISpriteInstance {},
	bloqueio_por_check_in: class extends self.ISpriteInstance {},
	parametro_no_piVision_fora_plano: class extends self.ISpriteInstance {},
	ranges_iguais: class extends self.ISpriteInstance {},
	seção_piscando: class extends self.ISpriteInstance {},
	erro_criar_receita_erro_memoria: class extends self.ISpriteInstance {},
	erro_criar_receita_variavel_nao_encontrada: class extends self.ISpriteInstance {},
	ErroAoCriarReceita_falha_data_base: class extends self.ISpriteInstance {},
	pi_point_nao_atualiza: class extends self.ISpriteInstance {},
	receita_codigo_cadastrado_pt_created: class extends self.ISpriteInstance {},
	receita_codigo_cadastrado_pt_created_: class extends self.ISpriteInstance {},
	tudo_configurado_mas_falta_subir_valores: class extends self.ISpriteInstance {},
	valor_pi_vision_diferente_valor_maquina: class extends self.ISpriteInstance {},
	variavel_desativada_afetando_conformidade: class extends self.ISpriteInstance {},
	variavel_desativada_afetando_conformidade2: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	bg2: class extends self.ISpriteInstance {},
	bt_reiniciar: class extends self.ISpriteInstance {},
	seta: class extends self.ISpriteInstance {},
	bg3: class extends self.ISpriteInstance {},
	tradutor: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	bt_home: class extends self.ISpriteInstance {},
	Navegador: class extends self.IInstance {}
}