const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Flash,
		C3.Plugins.AJAX,
		C3.Plugins.TextBox,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Internationalization,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Internationalization.Acts.LoadFromJSON,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Internationalization.Acts.SetLocale,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Internationalization.Exps.Lookup
	];
};
self.C3_JsPropNameTable = [
	{tx_1: 0},
	{tx_2: 0},
	{tx_3: 0},
	{Esmaecer: 0},
	{tx_4: 0},
	{tx_5: 0},
	{tx_6: 0},
	{tx_7: 0},
	{tx_8: 0},
	{tx_9: 0},
	{tx_10: 0},
	{tx_11: 0},
	{tx_12: 0},
	{tx_13: 0},
	{tx_14: 0},
	{tx_15: 0},
	{tx_16: 0},
	{tx_17: 0},
	{tx_18: 0},
	{tx_19: 0},
	{tx_20: 0},
	{tx_simples: 0},
	{bt_brasil: 0},
	{bt_china: 0},
	{bt_entrar: 0},
	{bt_espanha: 0},
	{bt_italia: 0},
	{bt_usa: 0},
	{bt_concluir: 0},
	{bt_blue: 0},
	{bt_orange: 0},
	{bt_home: 0},
	{bt_reiniciar: 0},
	{BT_OK: 0},
	{PSE_: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Senóide: 0},
	{seta_down: 0},
	{seta_left: 0},
	{seta_right: 0},
	{seta_up: 0},
	{Piscar: 0},
	{bg_1: 0},
	{bg_2: 0},
	{bg_3: 0},
	{bg_4: 0},
	{bg_5: 0},
	{bg_6: 0},
	{bg_clique: 0},
	{AJAX: 0},
	{EntradaDeTexto: 0},
	{Mouse: 0},
	{Teclado: 0},
	{tradutor: 0},
	{bandeiras: 0},
	{IdiomaSelecionado: 0}
];

self.InstanceType = {
	tx_1: class extends self.ITextInstance {},
	tx_2: class extends self.ITextInstance {},
	tx_3: class extends self.ITextInstance {},
	tx_4: class extends self.ITextInstance {},
	tx_5: class extends self.ITextInstance {},
	tx_6: class extends self.ITextInstance {},
	tx_7: class extends self.ITextInstance {},
	tx_8: class extends self.ITextInstance {},
	tx_9: class extends self.ITextInstance {},
	tx_10: class extends self.ITextInstance {},
	tx_11: class extends self.ITextInstance {},
	tx_12: class extends self.ITextInstance {},
	tx_13: class extends self.ITextInstance {},
	tx_14: class extends self.ITextInstance {},
	tx_15: class extends self.ITextInstance {},
	tx_16: class extends self.ITextInstance {},
	tx_17: class extends self.ITextInstance {},
	tx_18: class extends self.ITextInstance {},
	tx_19: class extends self.ITextInstance {},
	tx_20: class extends self.ITextInstance {},
	tx_simples: class extends self.ITextInstance {},
	bt_brasil: class extends self.ISpriteInstance {},
	bt_china: class extends self.ISpriteInstance {},
	bt_entrar: class extends self.ISpriteInstance {},
	bt_espanha: class extends self.ISpriteInstance {},
	bt_italia: class extends self.ISpriteInstance {},
	bt_usa: class extends self.ISpriteInstance {},
	bt_concluir: class extends self.ISpriteInstance {},
	bt_blue: class extends self.ISpriteInstance {},
	bt_orange: class extends self.ISpriteInstance {},
	bt_home: class extends self.ISpriteInstance {},
	bt_reiniciar: class extends self.ISpriteInstance {},
	BT_OK: class extends self.ISpriteInstance {},
	PSE_: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	seta_down: class extends self.ISpriteInstance {},
	seta_left: class extends self.ISpriteInstance {},
	seta_right: class extends self.ISpriteInstance {},
	seta_up: class extends self.ISpriteInstance {},
	bg_1: class extends self.ISpriteInstance {},
	bg_2: class extends self.ISpriteInstance {},
	bg_3: class extends self.ISpriteInstance {},
	bg_4: class extends self.ISpriteInstance {},
	bg_5: class extends self.ISpriteInstance {},
	bg_6: class extends self.ISpriteInstance {},
	bg_clique: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	tradutor: class extends self.IInstance {},
	bandeiras: class extends self.ISpriteInstance {}
}